name: Run API Tests and Publish Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Allure
        uses: allure-framework/actions/setup-allure@v1

      - name: Build and test with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Copy Allure Report to docs folder
        run: |
          mkdir -p docs
          cp -r target/site/allure-maven-plugin/* docs/

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}  # Seu token pessoal do GitHub Pages
          publish_dir: ./docs  # O diret칩rio onde o relat칩rio do Allure ser치 copiado
          target_branch: main  # Publica na branch 'main'
          user_name: 'GitHub Actions'  # Nome de usu치rio para o commit
          user_email: 'actions@github.com'  # E-mail para o commit
