name: Run API Tests and Publish Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean test -Dtest=suite.SuiteRunner

      - name: Set up Allure CLI
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_version: 2.27.0

      - name: Show Allure Results location
        run: |
          echo "Checking .allure-results directory:"
          if [ -d ".allure-results" ]; then
            echo ".allure-results exists. Files:"
            ls -la .allure-results
          else
            echo ".allure-results directory does NOT exist."
          fi

          echo ""
          echo "Checking target/allure-results directory:"
          if [ -d "target/allure-results" ]; then
            echo "target/allure-results exists. Files:"
            ls -la target/allure-results
          else
            echo "target/allure-results directory does NOT exist."
          fi

      - name: Copy Allure results to target folder
        run: |
            mkdir -p target/allure-results
            cp -r .allure-results/* target/allure-results/

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Copy Allure Report to docs folder
        run: |
          mkdir -p docs
          cp -r target/site/allure-maven-plugin/* docs/
          touch docs/.nojekyll

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./docs
          target_branch: gh-pages
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
