name: Run API Tests and Publish Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean test -Dtest=suite.SuiteRunner -Dallure.results.directory=target/allure-results

      - name: List directories to debug allure-results location
        run: |
          echo "Root files:"
          ls -la
          echo "Target files:"
          ls -la target
          echo ".allure-results files:"
          ls -la .allure-results || echo ".allure-results not found"

      - name: Copy allure results to target directory if exists
        run: |
          if [ -d ".allure-results" ]; then
            mkdir -p target/allure-results
            cp -r .allure-results/* target/allure-results/
          else
            echo ".allure-results directory does NOT exist. Skipping copy."
          fi

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Copy Allure Report to docs folder
        run: |
          mkdir -p docs
          cp -r target/site/allure-maven-plugin/* docs/
          touch docs/.nojekyll

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./docs
          target_branch: gh-pages
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
