name: Run API Tests and Publish Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Allure
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_version: 2.27.0

      - name: Build and test with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Copy Allure Report to docs folder
        run: |
          mkdir -p docs
          cp -r target/site/allure-maven-plugin/* docs/
          mv docs/allure-maven.html docs/index.html
          # Cria o arquivo .nojekyll para desabilitar o Jekyll
          touch docs/docs/.nojekyll

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./docs  # O diretório onde o relatório do Allure será copiado
          target_branch: gh-pages  # Publica na branch 'main'
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'